### ISSUE TITLE
Paleteria La Reyna is misspelled

### ISSUE THREAD

**Issue by tyrosinase** [imacrayon/whatthetofu#3]
(Currently "Renya")

**Comment by tyrosinase** [comment]
Also did I just not click enough, or is Wheat Street Dogs not there?

(Clicking got too depressing. Send some of La Reyna's al pastor to NJ plz.)

**Comment by tyrosinase** [comment]
(never mind, I looked at the source. Which is also depressing, but WSD is there at least.)

**Comment by imacrayon** [comment]
Good catch, thank you!

I should probably add a way to view the full list of places somewhere on the page...
